#+title: Kinematic Analysis of DC Motors under Constant Load
#+author: Abigail
#+options: toc:nil date:nil

#+property: header-args :session :results drawer :exports results
* Angular velocity as a function of time
In order to determine how a mechanism behave, it is first necessary to determine how a motor behaves. The thing that is generally useful for a mechanism is to figure out when it gets to a certain position---for that, it must be known when it gets to a certain position.

The equations of motion for a DC Motor and the way to obtain relevant constant values can be found in [[https://file.tavsys.net/control/controls-engineering-in-frc.pdf][Controls Engineering in the FIRST Robotics Competition]].

Since the battery and motor are in series, the equivalent resistance of the circuit is the sum of the internal resistance of the battery and the resistance of the motor.
\begin{equation}
V = I R_{eq} + \frac{\omega}{K_{v}}
\end{equation}

Current draw from a motor is equivalent to torque from the motor divided by $K_t$.
\begin{equation}
V = \frac{\tau}{K_{t}}R_{eq} + \frac{\omega}{K_{v}}
\end{equation}

The torque of the motor is equal to the torque accelerating the mechanism plus the load torque:
\begin{equation}
\tau=\tau_{accel }+ \tau_{load}
\end{equation}

$\tau_{accel}$ is equal to $J\alpha$ where $J$ is moment of inertia and $\alpha$ is angular acceleration.

\begin{equation}
\begin{aligned}
V &= \frac{J\alpha+\tau_{load}_{}}{K_{t}}R_{eq} + \frac{\omega}{K_{v}} \\
V &= \frac{JR_{eq}\alpha+R_{eq}\tau_{load}_{}}{K_{t}} + \frac{\omega}{K_{v}} \\
V &= \frac{JR_{eq}\alpha}{K_{t}} + \frac{R_{eq}\tau_{load}}{K_{t}}  + \frac{\omega}{K_{v}} \\
\end{aligned}
\end{equation}

Rewriting this in differential form:
\begin{equation}
V = \frac{JR_{eq}}{K_{t}}\frac{d\omega}{dt} + \frac{R_{eq}\tau_{load}}{K_{t}}  + \frac{\omega}{K_{v}}
\end{equation}

Isolating for $\frac{d\omega}{dt}$:
\begin{equation}
\begin{aligned}
V &= \frac{JR_{eq}}{K_{t}}\frac{d\omega}{dt} + \frac{R_{eq}\tau_{load}}{K_{t}}  + \frac{\omega}{K_{v}} \\
\frac{JR_{eq}}{K_{t}}\frac{d\omega}{dt} &= V - \frac{R_{eq}\tau_{load}}{K_{t}} - \frac{\omega}{K_{v}} \\
\frac{d\omega}{dt} &= \frac{K_t}{JR_{eq}_{}}V - \frac{1}{J}\tau_{load} - \frac{K_t}{JK_{v}R_{eq}}\omega \\
\end{aligned}
\end{equation}

Letting $A=-\frac{K_t}{JK_{v}R_{eq}}$ and $B=\frac{K_t}{JR_{eq}}V - \frac{1}{J}\tau_{load}$:
\begin{equation}
\frac{d\omega}{dt}=A\omega+B
\end{equation}

Solving for $\omega$:
\begin{equation}
\begin{aligned}
A\omega+B &= \frac{d\omega}{dt} \\
1 &= \frac{1}{A\omega+B}\frac{d\omega}{dt} \\
\int 1\,dt &= \int \frac{1}{A\omega+B} \,d\omega \\
t &= \frac{1}{A}ln(A\omega+B)+c_1 \\
t-c_1 &= \frac{1}{A}ln(A\omega+B) \\
A(t-c_1) &= ln(A\omega+B) \\
e^{A(t-c_1)} &= A\omega+B \\
e^{A(t-c_1)} -B &= A\omega \\
\frac{1}{A}e^{A(t-c_1)} - \frac{B}{A} &= \omega \\
\end{aligned}
\end{equation}

Solving for an arbitrary initial velocity:

\begin{equation}
\begin{aligned}
\frac{1}{A}e^{A(t-c_1)} - \frac{B}{A} &= \omega \\
\frac{1}{A}e^{A(0-c_1)} - \frac{B}{A} &= \omega_i \\
\frac{1}{A}e^{-Ac_1} - \frac{B}{A} &= \omega_i \\
e^{-Ac_1} - B &= A\omega_i \\
e^{-Ac_1} &= A\omega_i + B \\
-Ac_1 &= ln(A\omega_i + B) \\
c_1 &= -\frac{1}{A}ln(A\omega_i + B) \\
\end{aligned}
\end{equation}

* Angular Position as a function of time
Angular position is the integral of of angular velocity with respect to time:
\begin{equation}
\begin{aligned}
\theta &= \int \omega\,dt \\
\theta &= \int \frac{1}{A}e^{A(t-c_1)} - \frac{B}{A} \,dt \\
\theta &= \frac{1}{A^2}e^{A(t-c_1)} - \frac{B}{A}t + c_2 \\
\end{aligned}
\end{equation}

Solving for an arbitrary initial position:

\begin{equation}
\begin{aligned}
\theta &= \frac{1}{A^2}e^{A(t-c_1)} - \frac{B}{A}t + c_2 \\
\theta_i &= \frac{1}{A^2}e^{A(0-c_1)} - \frac{B}{A}0 + c_2 \\
\theta_i &= \frac{1}{A^2}e^{-Ac_1} + c_2 \\
c_2 &= \theta_i - \frac{1}{A^2}e^{-Ac_1} \\
\end{aligned}
\end{equation}

* Angular Acceleration as a function of time
Angular acceleration is the derivative of angular velocity with respect to time:
\begin{equation}
\begin{aligned}
\alpha &= \frac{d}{dt}\omega \\
\alpha &= \frac{d}{dt}\left(\frac{1}{A}e^{A(t-c_1)} - \frac{B}{A}\right) \\
\alpha &= \frac{A}{A}e^{A(t-c_1)} \\
\alpha &= e^{A(t-c_1)} \\
\end{aligned}
\end{equation}

* Linear loads
Linear mechanisms are useful in addition to angular ones, e.g. linear slides or a drivetrain.
** Equivalent Moment of Inertia
Linear mechanisms can be represented as an angular mechanism with a specific moment of inertia.
\begin{equation}
\begin{aligned}
\tau &= \tau \\
Fr &= J\alpha \\
(ma)r &= J\alpha \\
m(\alpha r)r &= J\alpha \\
m\alpha r^2 &= J\alpha \\
mr^2 &= J
\end{aligned}
\end{equation}
** Linear output
By multiplying the angular velocity and angular position functions by $r$, linear velocity and angular position can be found. The load torque is equal to $F_{load}r$.
